FROM python:3.7-slim

RUN apt-get update
RUN apt-get install git -y
RUN pip install virtualenv

# Just to speed up the flow testing
RUN virtualenv buddy-env \
 && . ./buddy-env/bin/activate \
 && pip install GitPython tensorboardX matplotlib wandb fabric cloudpickle PyYaml paramiko tqdm jax jaxlib

COPY test_scripts/test_flow.sh .

CMD ./test_flow.sh
